cd %~dp0
del *.~*
del *.ddp
del *.dcu
del *.dsk
del *.dsm
del *.bak
del *.map
del *.dpc
del *.drc
del *.local
del *.res
del *.stat
del *.identcache
del *.mes
rmdir __history/S
rmdir __recovery/S
rmdir VIT/S
rmdir Win32/S
rmdir Win64/S
rmdir LibrarySupport/S
rmdir ModelSupport_IMD_DC/S
rmdir out/S
rmdir ModelSupport_IMD_GB_CA410/S
rmdir .git/S
rmdir __history/S
rmdir __recovery/S